services:
  backend:
    build: 
      context: ./backend
    container_name: inventario-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
